import { InscripStudentEntity } from 'src/inscribe-student/inscribe-student.entity';
import { RespForumEntity } from 'src/forum/res-forum/res-forum.entity';
import { NoteRespForumEntity } from 'src/forum/note-res-forum/note-res-forum.entity';
import { ComentForumEntity } from 'src/forum/comment-forum/comment-forum.entity';
import { NoteComentForumEntity } from 'src/forum/note-comment-forum/note-comment-forum.entity';
import { NoteTasksEntity } from 'src/tasks/note-tasks/note-tasks.entity';
import { ResTasksEntity } from 'src/tasks/res-tasks/res-tasks.entity';
export declare class StudentEntity {
    id: number;
    cedula: string;
    nombres: string;
    apellidos?: string;
    nacimiento?: Date;
    telefono?: string;
    img?: string;
    pais?: string;
    ciudad?: string;
    direccion?: string;
    email: string;
    contraseña: string;
    estado: boolean;
    fechaCreacion: Date;
    inscripciones: InscripStudentEntity[];
    resForos: RespForumEntity[];
    noteResForos: NoteRespForumEntity[];
    commentForos: ComentForumEntity[];
    noteCommentForos: NoteComentForumEntity[];
    resActividades: ResTasksEntity[];
    notasActividades: NoteTasksEntity[];
    resExamen: NoteTasksEntity[];
    notasExamen: NoteTasksEntity[];
    hashPassword(): Promise<void>;
}
